font_family          family="MonaspiceNe Nerd Font"
modify_font          cell_height 2px
bold_font            auto
italic_font          auto
bold_italic_font     auto
window_padding_width 5 5 5 5
include              jellybeans.conf
cursor_shape         block
shell_integration    no-cursor
